on: 
 workflow_dispatch:
 issues:
  types:
    opened

env:
 VAR1: 'Ready for prod-ship it!'
 
name: Training Test Wf
jobs: 
 job1:
  name: Job1
  runs-on: ubuntu-latest
  steps:
    - run: echo 'Step 1 complete!'
    - run: echo 'Step 2 complete!'

 job2:
  name: Job2
  needs: [job1]
  runs-on: ubuntu-latest
  steps:
   - name: Cowsays
    # You may pin to the exact commit or the version.
    # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
     uses: mscoutermarsh/cowsays-action@v1
     with:
      # What does the cow say?
      text: ${{ env.VAR1 }}
      # Color of your cow
      color: magenta
          
